### ISSUE TITLE
Sim not inserted

### ISSUE THREAD

**Issue by ghost** [stephaneAG/SIM800L#2]
Hi, this isnt an issue off your library! But please help me.
My SIM800L wont recognize my SIM card.
The SIM card has NO pin (Id disabled the pin)

```
AT+CGATT
+CME ERROR: SIM not inserted

````
VCC voltage is 4.1V using an DC regulated power supply (max 2A).
The SIM card is inserted... Did you encounter that problem too?
Or do you may know what im missing?

Im sorry for my bad english.
Thanks in advance,
gamecompiler

**Comment by ghost** [comment]
Id found the solution. The sim card slots on some versions of the sim800l are so bad made, that im able to insert the sim card in two positions. So id inserted the sim card "wrong" (short side shows out). It works perfectly now. Id found many people discussing about that without any solution.

**Comment by MartinHanl** [comment]
> So id inserted the sim card "wrong" (short side shows out). 

Like so:
![image](https://user-images.githubusercontent.com/88330861/132598141-02ae7547-061e-436c-b419-3f56296592f9.png)

Isn't that the right way?
I'm asking because I'm having the same problem and I don't know how to fix it.
